# models: ['resnet18','resnet50','vit-s','vit-t','hybrid-s']
models: ['vit-s','vit-t','hybrid-s']
#models: ['resnet18']
train: 
  batch_size: 64
  num_workers: 8
  epochs: 100
  log_interval: 100
  val_interval: 10
  save_interval: 100
  checkpoint_path: './checkpoints'
  log_path: './logs'
  log_file: 'train.log'
optimizer:
  name: Adam
  lr: 0.001
  weight_decay: 0.0001
scheduler: